/* Generated By:JavaCC: Do not edit this line. SACParserCSS1Constants.java */
package com.steadystate.css.parser;

public interface SACParserCSS1Constants {

  int EOF = 0;
  int S = 1;
  int IDENT = 3;
  int LINK_PSCLASS = 4;
  int VISITED_PSCLASS = 5;
  int ACTIVE_PSCLASS = 6;
  int FIRST_LINE = 7;
  int FIRST_LETTER = 8;
  int HASH = 9;
  int LBRACE = 10;
  int RBRACE = 11;
  int COMMA = 12;
  int DOT = 13;
  int SEMICOLON = 14;
  int COLON = 15;
  int ASTERISK = 16;
  int SLASH = 17;
  int PLUS = 18;
  int MINUS = 19;
  int EQUALS = 20;
  int GT = 21;
  int LSQUARE = 22;
  int RSQUARE = 23;
  int STRING = 24;
  int RROUND = 25;
  int URL = 26;
  int CDO = 27;
  int CDC = 28;
  int IMPORT_SYM = 29;
  int IMPORTANT_SYM = 30;
  int ATKEYWORD = 31;
  int EMS = 32;
  int EXS = 33;
  int LENGTH_PX = 34;
  int LENGTH_CM = 35;
  int LENGTH_MM = 36;
  int LENGTH_IN = 37;
  int LENGTH_PT = 38;
  int LENGTH_PC = 39;
  int PERCENTAGE = 40;
  int NUMBER = 41;
  int RGB = 42;
  int NAME = 43;
  int D = 44;
  int NUM = 45;
  int UNICODERANGE = 46;
  int RANGE = 47;
  int Q16 = 48;
  int Q15 = 49;
  int Q14 = 50;
  int Q13 = 51;
  int Q12 = 52;
  int Q11 = 53;
  int NMSTART = 54;
  int NMCHAR = 55;
  int STRING1 = 56;
  int STRING2 = 57;
  int NONASCII = 58;
  int ESCAPE = 59;
  int NL = 60;
  int UNICODE = 61;
  int HNUM = 62;
  int H = 63;
  int UNKNOWN = 66;

  int DEFAULT = 0;
  int COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "\"/*\"",
    "<IDENT>",
    "\":link\"",
    "\":visited\"",
    "\":active\"",
    "\":first-line\"",
    "\":first-letter\"",
    "<HASH>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\":\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
    "<STRING>",
    "\")\"",
    "<URL>",
    "\"<!--\"",
    "\"-->\"",
    "\"@import\"",
    "<IMPORTANT_SYM>",
    "<ATKEYWORD>",
    "<EMS>",
    "<EXS>",
    "<LENGTH_PX>",
    "<LENGTH_CM>",
    "<LENGTH_MM>",
    "<LENGTH_IN>",
    "<LENGTH_PT>",
    "<LENGTH_PC>",
    "<PERCENTAGE>",
    "<NUMBER>",
    "\"rgb(\"",
    "<NAME>",
    "<D>",
    "<NUM>",
    "<UNICODERANGE>",
    "<RANGE>",
    "<Q16>",
    "<Q15>",
    "<Q14>",
    "<Q13>",
    "<Q12>",
    "\"?\"",
    "<NMSTART>",
    "<NMCHAR>",
    "<STRING1>",
    "<STRING2>",
    "<NONASCII>",
    "<ESCAPE>",
    "<NL>",
    "<UNICODE>",
    "<HNUM>",
    "<H>",
    "\"*/\"",
    "<token of kind 65>",
    "<UNKNOWN>",
  };

}
