/* Generated By:JavaCC: Do not edit this line. SACParserCSS21Constants.java */
package com.steadystate.css.parser;

public interface SACParserCSS21Constants {

  int EOF = 0;
  int S = 1;
  int W = 2;
  int LBRACE = 6;
  int RBRACE = 7;
  int COMMA = 8;
  int DOT = 9;
  int SEMICOLON = 10;
  int COLON = 11;
  int ASTERISK = 12;
  int SLASH = 13;
  int PLUS = 14;
  int MINUS = 15;
  int EQUALS = 16;
  int LSQUARE = 17;
  int RSQUARE = 18;
  int GREATER = 19;
  int HASH = 20;
  int STRING = 21;
  int RROUND = 22;
  int URL = 23;
  int URI = 24;
  int CDO = 25;
  int CDC = 26;
  int INCLUDES = 27;
  int DASHMATCH = 28;
  int IMPORT_SYM = 29;
  int PAGE_SYM = 30;
  int MEDIA_SYM = 31;
  int CHARSET_SYM = 32;
  int ATKEYWORD = 33;
  int IMPORTANT_KEYWORD = 34;
  int IMPORTANT_SYM = 35;
  int INHERIT = 36;
  int EMS = 37;
  int EXS = 38;
  int LENGTH_PX = 39;
  int LENGTH_CM = 40;
  int LENGTH_MM = 41;
  int LENGTH_IN = 42;
  int LENGTH_PT = 43;
  int LENGTH_PC = 44;
  int ANGLE_DEG = 45;
  int ANGLE_RAD = 46;
  int ANGLE_GRAD = 47;
  int TIME_MS = 48;
  int TIME_S = 49;
  int FREQ_HZ = 50;
  int FREQ_KHZ = 51;
  int DIMENSION = 52;
  int PERCENTAGE = 53;
  int NUMBER = 54;
  int FUNCTION = 55;
  int IDENT = 56;
  int NAME = 57;
  int NUM = 58;
  int Q16 = 59;
  int Q15 = 60;
  int Q14 = 61;
  int Q13 = 62;
  int Q12 = 63;
  int Q11 = 64;
  int NMSTART = 65;
  int NMCHAR = 66;
  int STRING1 = 67;
  int STRING2 = 68;
  int NONASCII = 69;
  int ESCAPE = 70;
  int NL = 71;
  int A_LETTER = 72;
  int C_LETTER = 73;
  int D_LETTER = 74;
  int E_LETTER = 75;
  int G_LETTER = 76;
  int H_LETTER = 77;
  int I_LETTER = 78;
  int K_LETTER = 79;
  int M_LETTER = 80;
  int N_LETTER = 81;
  int P_LETTER = 82;
  int R_LETTER = 83;
  int S_LETTER = 84;
  int T_LETTER = 85;
  int X_LETTER = 86;
  int Z_LETTER = 87;
  int UNICODE = 88;
  int HNUM = 89;
  int H = 90;
  int UNKNOWN = 91;

  int DEFAULT = 0;
  int COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "<W>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 5>",
    "<LBRACE>",
    "\"}\"",
    "<COMMA>",
    "\".\"",
    "\";\"",
    "\":\"",
    "\"*\"",
    "\"/\"",
    "<PLUS>",
    "\"-\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "<GREATER>",
    "<HASH>",
    "<STRING>",
    "\")\"",
    "<URL>",
    "<URI>",
    "\"<!--\"",
    "\"-->\"",
    "\"~=\"",
    "\"|=\"",
    "\"@import\"",
    "\"@page\"",
    "\"@media\"",
    "\"@charset \"",
    "<ATKEYWORD>",
    "\"important\"",
    "\"!\"",
    "\"inherit\"",
    "<EMS>",
    "<EXS>",
    "<LENGTH_PX>",
    "<LENGTH_CM>",
    "<LENGTH_MM>",
    "<LENGTH_IN>",
    "<LENGTH_PT>",
    "<LENGTH_PC>",
    "<ANGLE_DEG>",
    "<ANGLE_RAD>",
    "<ANGLE_GRAD>",
    "<TIME_MS>",
    "<TIME_S>",
    "<FREQ_HZ>",
    "<FREQ_KHZ>",
    "<DIMENSION>",
    "<PERCENTAGE>",
    "<NUMBER>",
    "<FUNCTION>",
    "<IDENT>",
    "<NAME>",
    "<NUM>",
    "<Q16>",
    "<Q15>",
    "<Q14>",
    "<Q13>",
    "<Q12>",
    "\"?\"",
    "<NMSTART>",
    "<NMCHAR>",
    "<STRING1>",
    "<STRING2>",
    "<NONASCII>",
    "<ESCAPE>",
    "<NL>",
    "<A_LETTER>",
    "<C_LETTER>",
    "<D_LETTER>",
    "<E_LETTER>",
    "<G_LETTER>",
    "<H_LETTER>",
    "<I_LETTER>",
    "<K_LETTER>",
    "<M_LETTER>",
    "<N_LETTER>",
    "<P_LETTER>",
    "<R_LETTER>",
    "<S_LETTER>",
    "<T_LETTER>",
    "<X_LETTER>",
    "<Z_LETTER>",
    "<UNICODE>",
    "<HNUM>",
    "<H>",
    "<UNKNOWN>",
  };

}
