/* Generated By:JavaCC: Do not edit this line. SACParserCSSmobileOKBasic1Constants.java */
package com.steadystate.css.parser;

public interface SACParserCSSmobileOKBasic1Constants {

  int EOF = 0;
  int S = 1;
  int IDENT = 3;
  int LINK_PSCLASS = 4;
  int VISITED_PSCLASS = 5;
  int ACTIVE_PSCLASS = 6;
  int FIRST_LINE = 7;
  int FIRST_LETTER = 8;
  int HASH = 9;
  int LBRACE = 10;
  int RBRACE = 11;
  int COMMA = 12;
  int DOT = 13;
  int SEMICOLON = 14;
  int COLON = 15;
  int ASTERISK = 16;
  int SLASH = 17;
  int PLUS = 18;
  int MINUS = 19;
  int EQUALS = 20;
  int GT = 21;
  int LSQUARE = 22;
  int RSQUARE = 23;
  int STRING = 24;
  int RROUND = 25;
  int URL = 26;
  int CDO = 27;
  int CDC = 28;
  int IMPORT_SYM = 29;
  int MEDIA_SYM = 30;
  int IMPORTANT_SYM = 31;
  int ATKEYWORD = 32;
  int EMS = 33;
  int EXS = 34;
  int LENGTH_PX = 35;
  int LENGTH_CM = 36;
  int LENGTH_MM = 37;
  int LENGTH_IN = 38;
  int LENGTH_PT = 39;
  int LENGTH_PC = 40;
  int PERCENTAGE = 41;
  int NUMBER = 42;
  int RGB = 43;
  int NAME = 44;
  int D = 45;
  int NUM = 46;
  int UNICODERANGE = 47;
  int RANGE = 48;
  int Q16 = 49;
  int Q15 = 50;
  int Q14 = 51;
  int Q13 = 52;
  int Q12 = 53;
  int Q11 = 54;
  int NMSTART = 55;
  int NMCHAR = 56;
  int STRING1 = 57;
  int STRING2 = 58;
  int NONASCII = 59;
  int ESCAPE = 60;
  int NL = 61;
  int UNICODE = 62;
  int HNUM = 63;
  int H = 64;
  int UNKNOWN = 67;

  int DEFAULT = 0;
  int COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "\"/*\"",
    "<IDENT>",
    "\":link\"",
    "\":visited\"",
    "\":active\"",
    "\":first-line\"",
    "\":first-letter\"",
    "<HASH>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\":\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
    "<STRING>",
    "\")\"",
    "<URL>",
    "\"<!--\"",
    "\"-->\"",
    "\"@import\"",
    "\"@media\"",
    "<IMPORTANT_SYM>",
    "<ATKEYWORD>",
    "<EMS>",
    "<EXS>",
    "<LENGTH_PX>",
    "<LENGTH_CM>",
    "<LENGTH_MM>",
    "<LENGTH_IN>",
    "<LENGTH_PT>",
    "<LENGTH_PC>",
    "<PERCENTAGE>",
    "<NUMBER>",
    "\"rgb(\"",
    "<NAME>",
    "<D>",
    "<NUM>",
    "<UNICODERANGE>",
    "<RANGE>",
    "<Q16>",
    "<Q15>",
    "<Q14>",
    "<Q13>",
    "<Q12>",
    "\"?\"",
    "<NMSTART>",
    "<NMCHAR>",
    "<STRING1>",
    "<STRING2>",
    "<NONASCII>",
    "<ESCAPE>",
    "<NL>",
    "<UNICODE>",
    "<HNUM>",
    "<H>",
    "\"*/\"",
    "<token of kind 66>",
    "<UNKNOWN>",
  };

}
